### ISSUE TITLE
Replace Task.Result With Task.GetAwaiter().GetResult() 

### ISSUE THREAD

**Issue by anktsrkr** [devmentors/DNC-DShop.Common#19]
There are several places where Task.Result is used. But my suggestion is to use Task.GetAwaiter().GetResult() instead of Task.Result, Please refer quotes from one of the [Microsoft's repo](https://github.com/aspnet/Security/issues/59)

> you should avoid using Task.Result and Task.Wait as much as possible as they always encapsulate the inner exception in an AggregateException and replace the message by a generic one (One or more errors occurred), which makes debugging harder. Even if the synchronous version shouldn't be used that often, you should strongly consider using Task.GetAwaiter().GetResult() instead

**Comment by GooRiOn** [comment]
Thanks for your remark, I'll create a PR for this 👍

**Comment by anktsrkr** [comment]
@GooRiOn great! Thanks. As you already merged the changes, closing this ticket.
